# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
  
development:
  adapter: sqlite3
  database: db/bandman_development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  database: db/bandman_test.sqlite3
  pool: 5
  timeout: 5000

production:
  database: bandman_production
  adapter: postgresql
  username: postgres

