# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username: postgres
  password: 1395.nl

development:
  <<: *common
  database: bandman_development
  
test:
  <<: *common
  database: bandman_test

production:
  <<: *common
  database: bandman_production
